/**
 * Aider Adapter
 *
 * Target: CONVENTIONS.md
 * Budget: 20K tokens
 * Write-back: File append via inbox mechanism
 * Session: No session support
 *
 * Aider reads configuration from .aider.conf.yml and conventions from
 * CONVENTIONS.md (or a file specified via --read flag). This adapter
 * writes context to a CONVENTIONS.md file that can be loaded by aider.
 * The YAML config is checked for detection but not modified.
 *
 * Aider does not support managed sections natively; content is written
 * as plain markdown.
 *
 * Detection looks for:
 * - .aider.conf.yml
 * - .aider/ directory
 */

import type {
  Adapter,
  AdapterCapabilityDeclaration,
  TargetToolCapabilities,
  DetectionResult,
  UniversalContext,
  TokenBudget,
  SyncResult,
  ExtractedLearnings,
  VerifyResult,
  FilesystemQuery,
} from '../types.js';

import { TOKEN_BUDGETS } from '../constants.js';
import {
  assembleContext,
  assembleEnhancedContext,
  buildFileWrite,
  buildSyncResult,
  extractLearningsFromText,
  verifyContentHash,
} from './base-adapter.js';
import type { CognitiveEnrichment } from './base-adapter.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const ADAPTER_ID = 'aider';
const DISPLAY_NAME = 'Aider';
const VERSION = '1.0.0';
const TARGET_FILE = 'CONVENTIONS.md';
const DETECTION_PATHS = ['.aider.conf.yml', '.aider'];

// ---------------------------------------------------------------------------
// Adapter
// ---------------------------------------------------------------------------

export function createAiderAdapter(): Adapter {
  const capabilities: AdapterCapabilityDeclaration = {
    canWriteBack: true,
    writeBackMechanism: 'file_append',
    canSubscribeEvents: false,
    canReportSessions: false,
    supportsStructuredCorrection: false,
  };

  const targetCapabilities: TargetToolCapabilities = {
    maxContextTokens: 100_000,
    supportsSystemPrompt: true,
    supportsFileWrites: true,
    supportsManagedSections: false,
  };

  return {
    id: ADAPTER_ID,
    displayName: DISPLAY_NAME,
    version: VERSION,
    capabilities,
    targetCapabilities,

    async detect(query: FilesystemQuery): Promise<DetectionResult> {
      const found: string[] = [];

      for (const path of DETECTION_PATHS) {
        if (await query.exists(path)) {
          found.push(path);
        }
      }

      const hasYaml = found.includes('.aider.conf.yml');

      return {
        detected: found.length > 0,
        confidence: hasYaml ? 0.95 : found.length > 0 ? 0.6 : 0,
        configPaths: hasYaml ? ['.aider.conf.yml'] : [],
      };
    },

    async transform(context: UniversalContext, budget: TokenBudget): Promise<SyncResult> {
      const effectiveBudget = Math.min(
        budget.remaining,
        TOKEN_BUDGETS[ADAPTER_ID],
      );
      const enrichment = context.cognitiveEnrichment as CognitiveEnrichment | undefined;
      const { content, tokensUsed } = enrichment
        ? assembleEnhancedContext(context, effectiveBudget, enrichment)
        : assembleContext(context, effectiveBudget);

      const header = `# Project Conventions (Noesis)\n\n> Auto-generated by Noesis. Load with: aider --read CONVENTIONS.md\n\n`;
      const fullContent = header + content;

      // Aider does not support managed sections, write as plain content
      const fileWrite = buildFileWrite(
        TARGET_FILE,
        fullContent,
        ADAPTER_ID,
        VERSION,
        false, // no managed sections
      );

      return buildSyncResult([fileWrite], tokensUsed);
    },

    async extractLearnings(content: string): Promise<ExtractedLearnings> {
      return extractLearningsFromText(content, ADAPTER_ID);
    },

    verify(content: string, expectedHash: string): VerifyResult {
      return verifyContentHash(content, expectedHash);
    },
  };
}
