/**
 * Generic Adapter
 *
 * Target: stdout or configurable file path
 * Budget: 10K tokens
 * Write-back: None (read-only fallback)
 * Session: No session support
 *
 * The generic adapter is a catch-all for tools not explicitly supported.
 * It writes context to a configurable output file (defaults to
 * .noesis-context.md) and does not use managed sections since the
 * target tool's format is unknown.
 *
 * Always detected with confidence 0.1 so it serves as the fallback
 * adapter when no other adapter matches.
 */

import type {
  Adapter,
  AdapterCapabilityDeclaration,
  TargetToolCapabilities,
  DetectionResult,
  UniversalContext,
  TokenBudget,
  SyncResult,
  ExtractedLearnings,
  VerifyResult,
  FilesystemQuery,
} from '../types.js';

import { TOKEN_BUDGETS } from '../constants.js';
import {
  assembleContext,
  assembleEnhancedContext,
  buildFileWrite,
  buildSyncResult,
  extractLearningsFromText,
  verifyContentHash,
} from './base-adapter.js';
import type { CognitiveEnrichment } from './base-adapter.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const ADAPTER_ID = 'generic';
const DISPLAY_NAME = 'Generic Adapter';
const VERSION = '1.0.0';
const DEFAULT_TARGET_FILE = '.noesis-context.md';

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

export interface GenericAdapterOptions {
  /** Output file path (relative to project root). */
  targetFile?: string;
  /** Token budget override. */
  maxTokens?: number;
}

// ---------------------------------------------------------------------------
// Adapter
// ---------------------------------------------------------------------------

export function createGenericAdapter(options?: GenericAdapterOptions): Adapter {
  const targetFile = options?.targetFile ?? DEFAULT_TARGET_FILE;
  const maxTokens = options?.maxTokens ?? TOKEN_BUDGETS[ADAPTER_ID];

  const capabilities: AdapterCapabilityDeclaration = {
    canWriteBack: false,
    writeBackMechanism: 'none',
    canSubscribeEvents: false,
    canReportSessions: false,
    supportsStructuredCorrection: false,
  };

  const targetCapabilities: TargetToolCapabilities = {
    maxContextTokens: maxTokens,
    supportsSystemPrompt: false,
    supportsFileWrites: true,
    supportsManagedSections: false,
  };

  return {
    id: ADAPTER_ID,
    displayName: DISPLAY_NAME,
    version: VERSION,
    capabilities,
    targetCapabilities,

    async detect(_query: FilesystemQuery): Promise<DetectionResult> {
      // Generic adapter is always available as a fallback, with low confidence
      return {
        detected: true,
        confidence: 0.1,
        configPaths: [],
      };
    },

    async transform(context: UniversalContext, budget: TokenBudget): Promise<SyncResult> {
      const effectiveBudget = Math.min(budget.remaining, maxTokens);
      const enrichment = context.cognitiveEnrichment as CognitiveEnrichment | undefined;
      const { content, tokensUsed } = enrichment
        ? assembleEnhancedContext(context, effectiveBudget, enrichment)
        : assembleContext(context, effectiveBudget);

      const header = `# Noesis Context\n\n> Generated by Noesis generic adapter.\n\n`;
      const fullContent = header + content;

      // Generic adapter does not use managed sections
      const fileWrite = buildFileWrite(
        targetFile,
        fullContent,
        ADAPTER_ID,
        VERSION,
        false, // no managed sections
      );

      return buildSyncResult([fileWrite], tokensUsed);
    },

    async extractLearnings(content: string): Promise<ExtractedLearnings> {
      return extractLearningsFromText(content, ADAPTER_ID);
    },

    verify(content: string, expectedHash: string): VerifyResult {
      return verifyContentHash(content, expectedHash);
    },
  };
}
